// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: concert.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_concert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_concert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_concert_proto_rawDescGZIP(), []int{0}
}

type Concert struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvailableTickets int32                  `protobuf:"varint,3,opt,name=available_tickets,json=availableTickets,proto3" json:"available_tickets,omitempty"`
	StartTime        string                 `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime          string                 `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Concert) Reset() {
	*x = Concert{}
	mi := &file_concert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Concert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Concert) ProtoMessage() {}

func (x *Concert) ProtoReflect() protoreflect.Message {
	mi := &file_concert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Concert.ProtoReflect.Descriptor instead.
func (*Concert) Descriptor() ([]byte, []int) {
	return file_concert_proto_rawDescGZIP(), []int{1}
}

func (x *Concert) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Concert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Concert) GetAvailableTickets() int32 {
	if x != nil {
		return x.AvailableTickets
	}
	return 0
}

func (x *Concert) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Concert) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type ConcertList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Concerts      []*Concert             `protobuf:"bytes,1,rep,name=concerts,proto3" json:"concerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConcertList) Reset() {
	*x = ConcertList{}
	mi := &file_concert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConcertList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConcertList) ProtoMessage() {}

func (x *ConcertList) ProtoReflect() protoreflect.Message {
	mi := &file_concert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConcertList.ProtoReflect.Descriptor instead.
func (*ConcertList) Descriptor() ([]byte, []int) {
	return file_concert_proto_rawDescGZIP(), []int{2}
}

func (x *ConcertList) GetConcerts() []*Concert {
	if x != nil {
		return x.Concerts
	}
	return nil
}

type BookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConcertId     int32                  `protobuf:"varint,1,opt,name=concert_id,json=concertId,proto3" json:"concert_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookRequest) Reset() {
	*x = BookRequest{}
	mi := &file_concert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookRequest) ProtoMessage() {}

func (x *BookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookRequest.ProtoReflect.Descriptor instead.
func (*BookRequest) Descriptor() ([]byte, []int) {
	return file_concert_proto_rawDescGZIP(), []int{3}
}

func (x *BookRequest) GetConcertId() int32 {
	if x != nil {
		return x.ConcertId
	}
	return 0
}

func (x *BookRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BookRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_concert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_concert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_concert_proto_rawDescGZIP(), []int{4}
}

func (x *BookResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_concert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_concert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_concert_proto_rawDescGZIP(), []int{5}
}

func (x *SearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_concert_proto protoreflect.FileDescriptor

const file_concert_proto_rawDesc = "" +
	"\n" +
	"\rconcert.proto\x12\x02pb\"\a\n" +
	"\x05Empty\"\x94\x01\n" +
	"\aConcert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12+\n" +
	"\x11available_tickets\x18\x03 \x01(\x05R\x10availableTickets\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\"6\n" +
	"\vConcertList\x12'\n" +
	"\bconcerts\x18\x01 \x03(\v2\v.pb.ConcertR\bconcerts\"a\n" +
	"\vBookRequest\x12\x1d\n" +
	"\n" +
	"concert_id\x18\x01 \x01(\x05R\tconcertId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"@\n" +
	"\fBookResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\rSearchRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xa2\x01\n" +
	"\x0eConcertService\x12)\n" +
	"\vGetConcerts\x12\t.pb.Empty\x1a\x0f.pb.ConcertList\x12/\n" +
	"\n" +
	"BookTicket\x12\x0f.pb.BookRequest\x1a\x10.pb.BookResponse\x124\n" +
	"\x0eSearchConcerts\x12\x11.pb.SearchRequest\x1a\x0f.pb.ConcertListB\x1dZ\x1bticket-reservation/proto;pbb\x06proto3"

var (
	file_concert_proto_rawDescOnce sync.Once
	file_concert_proto_rawDescData []byte
)

func file_concert_proto_rawDescGZIP() []byte {
	file_concert_proto_rawDescOnce.Do(func() {
		file_concert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_concert_proto_rawDesc), len(file_concert_proto_rawDesc)))
	})
	return file_concert_proto_rawDescData
}

var file_concert_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_concert_proto_goTypes = []any{
	(*Empty)(nil),         // 0: pb.Empty
	(*Concert)(nil),       // 1: pb.Concert
	(*ConcertList)(nil),   // 2: pb.ConcertList
	(*BookRequest)(nil),   // 3: pb.BookRequest
	(*BookResponse)(nil),  // 4: pb.BookResponse
	(*SearchRequest)(nil), // 5: pb.SearchRequest
}
var file_concert_proto_depIdxs = []int32{
	1, // 0: pb.ConcertList.concerts:type_name -> pb.Concert
	0, // 1: pb.ConcertService.GetConcerts:input_type -> pb.Empty
	3, // 2: pb.ConcertService.BookTicket:input_type -> pb.BookRequest
	5, // 3: pb.ConcertService.SearchConcerts:input_type -> pb.SearchRequest
	2, // 4: pb.ConcertService.GetConcerts:output_type -> pb.ConcertList
	4, // 5: pb.ConcertService.BookTicket:output_type -> pb.BookResponse
	2, // 6: pb.ConcertService.SearchConcerts:output_type -> pb.ConcertList
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_concert_proto_init() }
func file_concert_proto_init() {
	if File_concert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_concert_proto_rawDesc), len(file_concert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_concert_proto_goTypes,
		DependencyIndexes: file_concert_proto_depIdxs,
		MessageInfos:      file_concert_proto_msgTypes,
	}.Build()
	File_concert_proto = out.File
	file_concert_proto_goTypes = nil
	file_concert_proto_depIdxs = nil
}
